services:

  #currency service
  currency-php-fpm:
    build:
      context: currency
      dockerfile: ../docker/fpm/Dockerfile
    volumes:
      - ./currency:/usr/src/app

  currency-nginx:
    build:
      context: currency
      dockerfile: ../docker/nginx/Dockerfile
    volumes:
      - ./currency:/usr/src/app
    ports:
      - 4505:80
    depends_on:
      - currency-php-fpm

  #subscription service
  subscription-php-fpm:
    build:
      context: subscription
      dockerfile: ../docker/fpm/Dockerfile
    volumes:
      - ./subscription:/usr/src/app

  subscription-nginx:
    build:
      context: subscription
      dockerfile: ../docker/nginx/Dockerfile
    volumes:
      - ./subscription:/usr/src/app
    ports:
      - 4507:80
    depends_on:
      - subscription-php-fpm

  #smtp service
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025
      - 32770:1080
