services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Repository\Subscription\Command\SubscriptionCommandRepositoryInterface:
        class: App\Repository\Subscription\Command\TxtSubscriptionCommandRepository
        arguments:
            - "%kernel.project_dir%/test_system"

    App\Repository\Subscription\Query\SubscriptionQueryRepositoryInterface:
        class: App\Repository\Subscription\Query\TxtSubscriptionQueryRepository
        arguments:
            - "%kernel.project_dir%/test_system"

    App\Tests\Functional\Utils\TestCurrencyRateComparatorHandler: ~
    App\Utils\CurrencyRateComparator\CurrencyRateComparatorChainInterface: '@App\Tests\Functional\Utils\TestCurrencyRateComparatorHandler'