nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: GSES2 BTC subscription service
            version: 1.0.0
        servers:
            - url: /api
        tags:
            - name: subscription
              description: Робота з підпискою
        paths:
            /subscribe:
                post:
                    tags:
                        - subscription
                    summary: Підписати емейл на отримання поточного курсу
                    description: >-
                        Запит має перевірити, чи немає данної електронної адреси в поточній базі
                        даних (файловій) і, в разі її відсутності, записувати її. Пізніше, за
                        допомогою іншого запиту ми будемо відправляти лист на ті електронні
                        адреси, які будуть в цій базі.
                    operationId: subscribe
                    requestBody:
                        content:
                            application/x-www-form-urlencoded:
                                schema:
                                    required:
                                        - email
                                    properties:
                                        email:
                                            type: string
                                            description: Електронна адреса, яку потрібно підписати
                        required: true
                    responses:
                        '200':
                            description: E-mail додано
                            content: { }
                        '409':
                            description: Повертати, якщо e-mail вже є в базі даних (файловій)
                            content: { }
            /subscribers:
                get:
                    tags:
                        - subscription
                    summary: Отримати підписаних користувачів
                    operationId: subscribers
                    responses:
                        '200':
                            description: Повертається актуальний срисок користувачів
                            content:
                                application/json:
                                    schema:
                                        type: object

        components: { }

    areas: # to filter documented areas
        default:
            disable_default_routes: true