services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Tests\Functional\Utils\TestCurrencyRateComparatorChain: ~
    App\Application\CurrencyRateComparator\CurrencyRateComparatorChainInterface: '@App\Tests\Functional\Utils\TestCurrencyRateComparatorChain'